### PR TITLE
set label names in plot_recovery()

### PR DESCRIPTION
**Pull request by levolz**
qol change to allow to change label names if wanting something other than "ground truth" / "estimated"

### CODE REVIEW

**Comment by stefanradev93** [comment]
Pls add new arguments in the docstring of the function too.

**Comment by stefanradev93** [comment]
Pls also pull requests for Development, no direct pulls to master.

**Comment by levolz** [comment]
changed now - re: docstrings, `n_col` & `n_row` are not documented yet

**Comment by stefanradev93** [comment]
Nice. 10x, need to document those too.

**Comment by levolz** [comment]
Wasn't sure about style, though - instead of

`xlabel : 
   XXX
ylabel :
   YYY`

you could (for brevity) do

`xlabel, ylabel :
    XXX, YYY`

**Comment by stefanradev93** [comment]
As per convention, each arg gets its own line with type, default and a new line for description (see existing, looks nice when rendered).

**Pull request merged**
